In [30]:
import polars as pl

In [31]:
import pandas as pd

In [32]:
pd.__version__

'2.3.1'

In [33]:
pl.__version__

'1.33.1'

In [34]:
df = pl.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [35]:
df.head()

shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ engine_di ┆ num_cylin ┆ horsepowe ┆ vehicle_w ┆ … ┆ fuel_type ┆ drivetrai ┆ num_doors ┆ fuel_eff │
│ splacemen ┆ ders      ┆ r         ┆ eight     ┆   ┆ ---       ┆ n         ┆ ---       ┆ iciency_ │
│ t         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ i64       ┆ mpg      │
│ ---       ┆ i64       ┆ i64       ┆ f64       ┆   ┆           ┆ str       ┆           ┆ ---      │
│ i64       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 170       ┆ 3         ┆ 159       ┆ 3413.4337 ┆ … ┆ Gasoline  ┆ All-wheel ┆ 0         ┆ 13.23172 │
│           ┆           ┆           ┆ 59        ┆   ┆           ┆ drive     ┆           ┆ 9        │
│ 130       ┆ 5         ┆ 97        ┆ 3149.6649 ┆ … ┆ Gasoline  ┆ Front-whe ┆ 0         ┆ 13.68821 │
│           ┆           ┆           ┆ 34        ┆   ┆           ┆ el drive  ┆           ┆ 7        │
│ 170       ┆ null      ┆ 78        ┆ 3079.0389 ┆ … ┆ Gasoline  ┆ Front-whe ┆ 0         ┆ 14.24634 │
│           ┆           ┆           ┆ 97        ┆   ┆           ┆ el drive  ┆           ┆ 1        │
│ 220       ┆ 4         ┆ null      ┆ 2542.3924 ┆ … ┆ Diesel    ┆ All-wheel ┆ 2         ┆ 16.91273 │
│           ┆           ┆           ┆ 02        ┆   ┆           ┆ drive     ┆           ┆ 6        │
│ 210       ┆ 1         ┆ 140       ┆ 3460.8709 ┆ … ┆ Gasoline  ┆ All-wheel ┆ 2         ┆ 12.48836 │
│           ┆           ┆           ┆ 9         ┆   ┆           ┆ drive     ┆           ┆ 9        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [36]:
df.count()

shape: (1, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ engine_di ┆ num_cylin ┆ horsepowe ┆ vehicle_w ┆ … ┆ fuel_type ┆ drivetrai ┆ num_doors ┆ fuel_eff │
│ splacemen ┆ ders      ┆ r         ┆ eight     ┆   ┆ ---       ┆ n         ┆ ---       ┆ iciency_ │
│ t         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ u32       ┆ ---       ┆ u32       ┆ mpg      │
│ ---       ┆ u32       ┆ u32       ┆ u32       ┆   ┆           ┆ u32       ┆           ┆ ---      │
│ u32       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 9704      ┆ 9222      ┆ 8996      ┆ 9704      ┆ … ┆ 9704      ┆ 9704      ┆ 9202      ┆ 9704     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [37]:
df.shape

(9704, 11)

In [8]:
df.unique('fuel_type').count()

shape: (1, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ engine_di ┆ num_cylin ┆ horsepowe ┆ vehicle_w ┆ … ┆ fuel_type ┆ drivetrai ┆ num_doors ┆ fuel_eff │
│ splacemen ┆ ders      ┆ r         ┆ eight     ┆   ┆ ---       ┆ n         ┆ ---       ┆ iciency_ │
│ t         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ u32       ┆ ---       ┆ u32       ┆ mpg      │
│ ---       ┆ u32       ┆ u32       ┆ u32       ┆   ┆           ┆ u32       ┆           ┆ ---      │
│ u32       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2         ┆ 2         ┆ 1         ┆ 2         ┆ … ┆ 2         ┆ 2         ┆ 2         ┆ 2        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
df.null_count()

shape: (1, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ engine_di ┆ num_cylin ┆ horsepowe ┆ vehicle_w ┆ … ┆ fuel_type ┆ drivetrai ┆ num_doors ┆ fuel_eff │
│ splacemen ┆ ders      ┆ r         ┆ eight     ┆   ┆ ---       ┆ n         ┆ ---       ┆ iciency_ │
│ t         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ u32       ┆ ---       ┆ u32       ┆ mpg      │
│ ---       ┆ u32       ┆ u32       ┆ u32       ┆   ┆           ┆ u32       ┆           ┆ ---      │
│ u32       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 482       ┆ 708       ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 502       ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
count = (df.null_count() > 0).sum_horizontal().item()
print(f"Columns with nulls: {count}") 

Columns with nulls: 4


In [11]:
df.filter(pl.col('origin')=='Asia')['fuel_efficiency_mpg'].max()

23.759122836520497

In [12]:
### Q6
print(f"Print median horse power {df['horsepower'].median()}")
print(f"Print mode horse power {df['horsepower'].drop_nulls().mode().item()}")
column_mode = df['horsepower'].drop_nulls().mode().item()
df_2 = df.with_columns(
    pl.col('horsepower').fill_null(column_mode).alias('horsepower')
)
print(f"Print median horse power {df_2['horsepower'].median()}")

Print median horse power 149.0
Print mode horse power 152
Print median horse power 152.0


In [16]:
### Q7 
df.filter(pl.col('origin')=='Asia')['vehicle_weight','model_year'].head(7)

shape: (7, 2)
┌────────────────┬────────────┐
│ vehicle_weight ┆ model_year │
│ ---            ┆ ---        │
│ f64            ┆ i64        │
╞════════════════╪════════════╡
│ 2714.21931     ┆ 2016       │
│ 2783.868974    ┆ 2010       │
│ 3582.687368    ┆ 2007       │
│ 2231.808142    ┆ 2011       │
│ 2659.431451    ┆ 2016       │
│ 2844.227534    ┆ 2014       │
│ 3761.994038    ┆ 2019       │
└────────────────┴────────────┘

In [18]:
X = df.filter(pl.col('origin')=='Asia')['vehicle_weight','model_year'].head(7).to_numpy()

In [19]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [20]:
import numpy as np

In [21]:
XTX = X.T @ X

In [22]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [23]:
np.linalg.inv(XTX)

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [26]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [27]:
np.linalg.inv(XTX) @ X.T @ y

array([0.01386421, 0.5049067 ])

In [28]:
w = np.linalg.inv(XTX) @ X.T @ y

In [29]:
w.sum()

np.float64(0.5187709081074016)